# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 728)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1321, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 20, 1253, 503))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.taskBox = QtWidgets.QComboBox(self.frame)
        self.taskBox.setMinimumSize(QtCore.QSize(280, 0))
        self.taskBox.setObjectName("taskBox")
        self.taskBox.addItem("")
        self.taskBox.addItem("")
        self.horizontalLayout.addWidget(self.taskBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.taskListWidget = QtWidgets.QListWidget(self.frame)
        self.taskListWidget.setObjectName("taskListWidget")
        self.verticalLayout.addWidget(self.taskListWidget)
        self.taskTextBrowser = QtWidgets.QTextBrowser(self.frame)
        self.taskTextBrowser.setObjectName("taskTextBrowser")
        self.verticalLayout.addWidget(self.taskTextBrowser)
        self.horizontalLayout_6.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.minBox = QtWidgets.QSpinBox(self.frame_2)
        self.minBox.setMaximum(59)
        self.minBox.setObjectName("minBox")
        self.gridLayout.addWidget(self.minBox, 1, 0, 1, 1)
        self.hourBox = QtWidgets.QSpinBox(self.frame_2)
        self.hourBox.setMaximum(23)
        self.hourBox.setObjectName("hourBox")
        self.gridLayout.addWidget(self.hourBox, 1, 1, 1, 1)
        self.cronSetButton = QtWidgets.QPushButton(self.frame_2)
        self.cronSetButton.setObjectName("cronSetButton")
        self.gridLayout.addWidget(self.cronSetButton, 1, 2, 1, 1)
        self.minCheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.minCheckBox.setObjectName("minCheckBox")
        self.gridLayout.addWidget(self.minCheckBox, 2, 0, 1, 1)
        self.hourCheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.hourCheckBox.setObjectName("hourCheckBox")
        self.gridLayout.addWidget(self.hourCheckBox, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.domLabel = QtWidgets.QLabel(self.frame_2)
        self.domLabel.setObjectName("domLabel")
        self.gridLayout_2.addWidget(self.domLabel, 0, 2, 1, 1)
        self.dayBox = QtWidgets.QComboBox(self.frame_2)
        self.dayBox.setObjectName("dayBox")
        self.dayBox.addItem("")
        self.dayBox.addItem("")
        self.dayBox.addItem("")
        self.dayBox.addItem("")
        self.dayBox.addItem("")
        self.dayBox.addItem("")
        self.dayBox.addItem("")
        self.dayBox.addItem("")
        self.gridLayout_2.addWidget(self.dayBox, 1, 0, 1, 1)
        self.monthBox = QtWidgets.QSpinBox(self.frame_2)
        self.monthBox.setMaximum(12)
        self.monthBox.setObjectName("monthBox")
        self.gridLayout_2.addWidget(self.monthBox, 1, 1, 1, 1)
        self.domBox = QtWidgets.QSpinBox(self.frame_2)
        self.domBox.setMaximum(31)
        self.domBox.setObjectName("domBox")
        self.gridLayout_2.addWidget(self.domBox, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.atSetButton = QtWidgets.QPushButton(self.frame_2)
        self.atSetButton.setObjectName("atSetButton")
        self.horizontalLayout_7.addWidget(self.atSetButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_2)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(268, 0))
        self.dateTimeEdit.setDate(QtCore.QDate(2019, 9, 9))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_3.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setMinimumSize(QtCore.QSize(133, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.atSpinBox = QtWidgets.QSpinBox(self.frame_2)
        self.atSpinBox.setObjectName("atSpinBox")
        self.horizontalLayout_2.addWidget(self.atSpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.atComboBox = QtWidgets.QComboBox(self.frame_2)
        self.atComboBox.setObjectName("atComboBox")
        self.atComboBox.addItem("")
        self.atComboBox.addItem("")
        self.atComboBox.addItem("")
        self.atComboBox.addItem("")
        self.atComboBox.addItem("")
        self.atComboBox.addItem("")
        self.gridLayout_3.addWidget(self.atComboBox, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.taskHelpTextBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.taskHelpTextBrowser.setObjectName("taskHelpTextBrowser")
        self.verticalLayout_2.addWidget(self.taskHelpTextBrowser)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.submitButton = QtWidgets.QPushButton(self.frame_3)
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout_3.addWidget(self.submitButton)
        self.exitButton = QtWidgets.QPushButton(self.frame_3)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_3.addWidget(self.exitButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(40, 30, 1251, 551))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pastListWidget = QtWidgets.QListWidget(self.frame_4)
        self.pastListWidget.setObjectName("pastListWidget")
        self.verticalLayout_4.addWidget(self.pastListWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pastButton = QtWidgets.QPushButton(self.frame_4)
        self.pastButton.setObjectName("pastButton")
        self.horizontalLayout_4.addWidget(self.pastButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_5 = QtWidgets.QFrame(self.tab_3)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 1281, 551))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.presentListWidget = QtWidgets.QListWidget(self.frame_5)
        self.presentListWidget.setObjectName("presentListWidget")
        self.verticalLayout_5.addWidget(self.presentListWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addButton = QtWidgets.QPushButton(self.frame_5)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_5.addWidget(self.addButton)
        self.delButton = QtWidgets.QPushButton(self.frame_5)
        self.delButton.setObjectName("delButton")
        self.horizontalLayout_5.addWidget(self.delButton)
        self.editButton = QtWidgets.QPushButton(self.frame_5)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout_5.addWidget(self.editButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 34))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Options = QtWidgets.QMenu(self.menubar)
        self.menu_Options.setObjectName("menu_Options")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionConfiguration = QtWidgets.QAction(MainWindow)
        self.actionConfiguration.setObjectName("actionConfiguration")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionExit)
        self.menu_Options.addAction(self.actionConfiguration)
        self.menu_Help.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Task"))
        self.taskBox.setItemText(0, _translate("MainWindow", "Select Category ..."))
        self.taskBox.setItemText(1, _translate("MainWindow", "All"))
        self.label_2.setText(_translate("MainWindow", "Run job every with Cron"))
        self.label_3.setText(_translate("MainWindow", "Min"))
        self.label_4.setText(_translate("MainWindow", "Hour"))
        self.cronSetButton.setText(_translate("MainWindow", "Set Cron"))
        self.minCheckBox.setText(_translate("MainWindow", "*"))
        self.hourCheckBox.setText(_translate("MainWindow", "*"))
        self.label_5.setText(_translate("MainWindow", "Weekday"))
        self.label_6.setText(_translate("MainWindow", "MM"))
        self.domLabel.setText(_translate("MainWindow", "DD"))
        self.dayBox.setItemText(0, _translate("MainWindow", "Select ..."))
        self.dayBox.setItemText(1, _translate("MainWindow", "Mon ..."))
        self.dayBox.setItemText(2, _translate("MainWindow", "Tue"))
        self.dayBox.setItemText(3, _translate("MainWindow", "Wed"))
        self.dayBox.setItemText(4, _translate("MainWindow", "Thu"))
        self.dayBox.setItemText(5, _translate("MainWindow", "Fri"))
        self.dayBox.setItemText(6, _translate("MainWindow", "Sat"))
        self.dayBox.setItemText(7, _translate("MainWindow", "Sun"))
        self.label_8.setText(_translate("MainWindow", "Run Job Once with @"))
        self.atSetButton.setText(_translate("MainWindow", "Set @"))
        self.label_9.setText(_translate("MainWindow", "Run@Once"))
        self.label_10.setText(_translate("MainWindow", "Run@Now+"))
        self.atComboBox.setItemText(0, _translate("MainWindow", "Select ..."))
        self.atComboBox.setItemText(1, _translate("MainWindow", "Min"))
        self.atComboBox.setItemText(2, _translate("MainWindow", "Hour"))
        self.atComboBox.setItemText(3, _translate("MainWindow", "Day"))
        self.atComboBox.setItemText(4, _translate("MainWindow", "Week"))
        self.atComboBox.setItemText(5, _translate("MainWindow", "Month"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tasks"))
        self.pastButton.setText(_translate("MainWindow", "View Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Past"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.delButton.setText(_translate("MainWindow", "Delete"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Present"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Options.setTitle(_translate("MainWindow", "&Options"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionConfiguration.setText(_translate("MainWindow", "Configuration"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

